# Generated by Django 4.0.3 on 2022-04-13 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=500)),
                ('trailer', models.URLField(default='https://www.youtube.com/watch?v=iw_wt2hHW2w')),
                ('synopsis', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='movies')),
                ('slug', models.SlugField(null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=9000))),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_id', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('number_seats', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentcard',
            name='card_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='card_number',
            field=encrypted_model_fields.fields.EncryptedIntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='expiration_date',
            field=encrypted_model_fields.fields.EncryptedDateField(),
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2022, 4, 13))),
                ('time', models.TimeField(default=datetime.time(9, 30))),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie')),
                ('show_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.showroom')),
            ],
        ),
    ]
