# Generated by Django 4.0.3 on 2022-04-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_movie_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('number_tickets', models.IntegerField()),
                ('booking_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField()),
                ('ticket_type', models.CharField(choices=[('C', 'Child'), ('A', 'Adult'), ('S', 'Senior')], default='A', max_length=1)),
            ],
        ),
    ]
