# Generated by Django 4.0.3 on 2022-04-17 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_booking_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 17)),
        ),
    ]
