# Generated by Django 4.0.3 on 2022-04-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_booking_id_alter_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
