# Generated by Django 4.0.3 on 2022-04-23 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_promotion_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(default='inactive', max_length=100),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 23)),
        ),
    ]
