# Generated by Django 4.0.3 on 2022-04-27 00:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_promotion_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='showtime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.showroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showtime',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 26)),
        ),
    ]
