# Generated by Django 4.0.3 on 2022-04-27 02:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_ticket_booking_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='showtime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.showtime'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 26)),
        ),
    ]
