# Generated by Django 4.0.3 on 2022-04-27 04:10

import datetime
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_showtime_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_tickets',
        ),
        migrations.AddField(
            model_name='booking',
            name='number_adult',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_child',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_senior',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 27)),
        ),
    ]
