# Generated by Django 4.0.3 on 2022-05-02 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_showtime_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_price', models.IntegerField(blank=True, default='5', null=True)),
                ('adult_price', models.IntegerField(blank=True, default='10', null=True)),
                ('senior_price', models.IntegerField(blank=True, default='15', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='showtime',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 2)),
        ),
    ]
