# Generated by Django 4.0.3 on 2022-05-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_ticketprice_alter_showtime_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketPrice',
            new_name='TicketType',
        ),
    ]
