# Generated by Django 4.0.3 on 2022-05-04 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_ticketprice_tickettype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 4)),
        ),
    ]
