# Generated by Django 4.0.3 on 2022-05-03 21:02

import datetime
from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_ticketprice_tickettype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='card_number',
            field=encrypted_model_fields.fields.EncryptedIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='expiration_date',
            field=encrypted_model_fields.fields.EncryptedDateField(blank=True),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 3)),
        ),
    ]
