# Generated by Django 4.0.3 on 2022-05-03 21:16

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_paymentcard_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='card_number',
            field=encrypted_model_fields.fields.EncryptedIntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='expiration_date',
            field=encrypted_model_fields.fields.EncryptedDateField(),
        ),
    ]
