# Generated by Django 4.0.3 on 2022-05-05 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_showtime_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 5)),
        ),
    ]
