# Generated by Django 4.0.3 on 2022-05-04 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_paymentcard_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 4)),
        ),
    ]
